# Generated by Django 5.2.3 on 2025-06-22 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('diretores', '0001_initial'),
        ('generos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=500)),
                ('data_lancamento', models.DateField(blank=True, null=True)),
                ('sinopse', models.TextField(blank=True, null=True)),
                ('diretor', models.ManyToManyField(related_name='jogos', to='diretores.diretor')),
                ('genero', models.ManyToManyField(related_name='jogos', to='generos.genero')),
            ],
        ),
    ]
