# Generated by Django 5.2.7 on 2025-11-11 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('desenvolvedora', '0001_initial'),
        ('jogos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jogo',
            name='desenvolvedora',
            field=models.ManyToManyField(related_name='jogos', to='desenvolvedora.desenvolvedora'),
        ),
    ]
