# Generated by Django 5.2.3 on 2025-06-21 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Diretor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('data_nascimento', models.DateField(blank=True, null=True)),
                ('nacionalidade', models.CharField(blank=True, choices=[('EUA', 'Estados Unidos'), ('JPN', 'Japão')], max_length=100, null=True)),
            ],
        ),
    ]
