# Generated by Django 5.2.3 on 2025-06-23 21:15

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('jogos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estrelas', models.IntegerField(validators=[django.core.validators.MinValueValidator(0, 'A avaliação não pode ser inferior a 0 estrelas'), django.core.validators.MaxValueValidator(5, 'A avaliação não pode ser inferior a 0 estrelas')])),
                ('analise', models.TextField(blank=True, null=True)),
                ('jogo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reviews', to='jogos.jogo')),
            ],
        ),
    ]
