# Generated by Django 5.2.4 on 2025-08-13 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='analise',
        ),
        migrations.AddField(
            model_name='review',
            name='review',
            field=models.TextField(blank=True, null=True),
        ),
    ]
