# Generated by Django 5.2.4 on 2025-08-13 21:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_remove_review_analise_review_review'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='review',
            new_name='analise',
        ),
    ]
